#+TITLE: TNH-Emacs
#+AUTHOR: Leo Olofsson

TNH-Emacs, is my personal emacs configuration. That I am customizing after my needs.

* Installation

** Platforms supported

| Linux   | Yes |
| Windows | No  |
| MacOS   | No  |

This Emacs configuration is currently only tested on =Arch Linux=.

** Emacs
#+begin_quote
I am currently running Emacs =28.0.50= =Master= Branch, the repo is *only* tested on Version =28.0.50=.
#+end_quote

*** Arch-linux
*Recomended* Install Emacs =28.0.50= or above.

#+begin_src shell
paru -S emacs-git
#+end_src

*** Post installation 
Clone this repository to the =.emacs.d/= directory.
#+begin_src shell
git clone https://github.com/TheNerdyHamster/tnh-emacs.git ~/.config/emacs
#+end_src

**** Icons 
Packages such as =Centaur-tabs=, =Treemacs=, =doom-modeline= utilizes features from =all-the-icons=.

When you start up emacs for the first time, run the following command.
#+begin_src emacs-lisp
M-x (all-the-icons-install-font)
#+end_src


* Inspiration
[[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]] provides a good list of useful packages.

Other emacs/dotfiles repos for inspiration
- [[https://github.com/daviwil/dotfiles][Daviwil's dotfiles]]
- [[https://github.com/daviwil/emacs-from-scratch][Daviwil's emacs from scratch repo]]
- [[https://github.com/angrybacon/dotemacs][Angrybacon's dotemacs]]
